### ISSUE TITLE
Add option to run PoT only to calculate similarity

### ISSUE THREAD

**Issue by cafed00d4j** [chrismattmann/pooled_time_series#17]
Given a set of *of.txt and *.hog.txt files from a previous run we can invoke PoT's similarity calculation logic to get the similarity matrix

OR to put it another way

Separate out the similarity calculation logic in PoT

**Comment by chrismattmann** [comment]
@cafed00d4j did you get this done? Can you submit a PR?

**Comment by chrismattmann** [comment]
cc @MJJoyce

**Comment by cafed00d4j** [comment]
Will submit a PR later today.

**Comment by chrismattmann** [comment]
thanks @cafed00d4j

**Comment by chrismattmann** [comment]
ping @cafed00d4j did you submit the PR?

**Comment by cafed00d4j** [comment]
I ran into some difficulties in separating out the calculateSimilarity() function..
It takes an list of FeatureVectors. I think these are the *.of.txt and *.hog.txt vectors.
However, I ran into build issues. I'm still working on it. 


I will try to submit the PR today. Or in the worst case before the end of the weekend

**Comment by chrismattmann** [comment]
thanks @cafed00d4j !

**Comment by cafed00d4j** [comment]
Hi prof. @chrismattmann 

please find the pull request here
https://github.com/chrismattmann/pooled_time_series/pull/18

thanks

**Comment by chrismattmann** [comment]
Done!

**Comment by chrismattmann** [comment]
Thanks @cafed00d4j did the run complete?

**Comment by cafed00d4j** [comment]
Its still running.

Its on file 5XX9/8XXX (IIRC)

[image: Inline image 1]

Its become extremely slow at this point. I havent seen anything printed to
log yet. The last line it printed was the current file being processed
(5XX9 IIRC. Sorry I forgot to take a screenshot before running ps above)

But I can see that its still running and taking up CPU time. So i don't
think it crashed of stopped




adi
