### ISSUE TITLE
Add script to format the input

### ISSUE THREAD

**Issue by soumyaravi** [chrismattmann/pooled_time_series#24]
A script or two to format the input into the expected formats for MeanChiSquare/Similarity jobs.

**Comment by soumyaravi** [comment]
@chrismattmann Currently I am not changing Mike's script since it works according to what I need for the formatted Similarity output

**Comment by chrismattmann** [comment]
+1 great so what's this issue about then if we're not changing Mike's script?

**Comment by soumyaravi** [comment]
Mike had mentioned that it was just a rough first pass that he had written, that may need work.

**Comment by chrismattmann** [comment]
gotcha, so you will update it @soumyaravi ?

**Comment by soumyaravi** [comment]
@chrismattmann Yes, I plan on updating it after running the tests

**Comment by chrismattmann** [comment]
solved in #33
